const COUNTRIES = [
  { country: "United States", city: "New York", code: "JFK" },
  { country: "Canada", city: "Toronto", code: "YYZ" },
  { country: "Mexico", city: "Mexico City", code: "MEX" },
  { country: "Brazil", city: "São Paulo", code: "GRU" },
  { country: "Argentina", city: "Buenos Aires", code: "EZE" },
  { country: "Chile", city: "Santiago", code: "SCL" },
  { country: "Colombia", city: "Bogotá", code: "BOG" },
  { country: "Peru", city: "Lima", code: "LIM" },
  { country: "Panama", city: "Panama City", code: "PTY" },
  { country: "United Kingdom", city: "London", code: "LHR" },
  { country: "Ireland", city: "Dublin", code: "DUB" },
  { country: "France", city: "Paris", code: "CDG" },
  { country: "Germany", city: "Berlin", code: "BER" },
  { country: "Netherlands", city: "Amsterdam", code: "AMS" },
  { country: "Belgium", city: "Brussels", code: "BRU" },
  { country: "Spain", city: "Madrid", code: "MAD" },
  { country: "Portugal", city: "Lisbon", code: "LIS" },
  { country: "Italy", city: "Rome", code: "FCO" },
  { country: "Switzerland", city: "Zurich", code: "ZRH" },
  { country: "Austria", city: "Vienna", code: "VIE" },
  { country: "Poland", city: "Warsaw", code: "WAW" },
  { country: "Czechia", city: "Prague", code: "PRG" },
  { country: "Hungary", city: "Budapest", code: "BUD" },
  { country: "Romania", city: "Bucharest", code: "OTP" },
  { country: "Greece", city: "Athens", code: "ATH" },
  { country: "Cyprus", city: "Larnaca", code: "LCA" },
  { country: "Sweden", city: "Stockholm", code: "ARN" },
  { country: "Norway", city: "Oslo", code: "OSL" },
  { country: "Denmark", city: "Copenhagen", code: "CPH" },
  { country: "Finland", city: "Helsinki", code: "HEL" },
  { country: "Iceland", city: "Reykjavík", code: "KEF" },
  { country: "Estonia", city: "Tallinn", code: "TLL" },
  { country: "United Arab Emirates", city: "Dubai", code: "DXB" },
  { country: "Saudi Arabia", city: "Riyadh", code: "RUH" },
  { country: "Qatar", city: "Doha", code: "DOH" },
  { country: "Bahrain", city: "Manama", code: "BAH" },
  { country: "Morocco", city: "Casablanca", code: "CMN" },
  { country: "Egypt", city: "Cairo", code: "CAI" },
  { country: "Kenya", city: "Nairobi", code: "NBO" },
  { country: "Nigeria", city: "Lagos", code: "LOS" },
  { country: "South Africa", city: "Johannesburg", code: "JNB" },
  { country: "Ethiopia", city: "Addis Ababa", code: "ADD" },
  { country: "India", city: "Mumbai", code: "BOM" },
  { country: "Singapore", city: "Singapore", code: "SIN" },
  { country: "Thailand", city: "Bangkok", code: "BKK" },
  { country: "Vietnam", city: "Ho Chi Minh City", code: "SGN" },
  { country: "Philippines", city: "Manila", code: "MNL" },
  { country: "Indonesia", city: "Jakarta", code: "CGK" },
  { country: "Malaysia", city: "Kuala Lumpur", code: "KUL" },
  { country: "Hong Kong", city: "Hong Kong", code: "HKG" },
  { country: "Japan", city: "Tokyo", code: "HND" },
  { country: "South Korea", city: "Seoul", code: "ICN" },
  { country: "Taiwan", city: "Taipei", code: "TPE" },
  { country: "Australia", city: "Sydney", code: "SYD" },
  { country: "New Zealand", city: "Auckland", code: "AKL" },
  { country: "Georgia", city: "Tbilisi", code: "TBS" },
  { country: "Kazakhstan", city: "Almaty", code: "ALA" },
  { country: "Uzbekistan", city: "Tashkent", code: "TAS" },
];
